package per.zpp.mapper;

import per.zpp.domain.Admin;

import java.util.Map;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_admin
     *
     * @mbggenerated Thu Aug 24 08:59:59 CST 2023
     */
    int deleteByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_admin
     *
     * @mbggenerated Thu Aug 24 08:59:59 CST 2023
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_admin
     *
     * @mbggenerated Thu Aug 24 08:59:59 CST 2023
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_admin
     *
     * @mbggenerated Thu Aug 24 08:59:59 CST 2023
     */
    Admin selectByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_admin
     *
     * @mbggenerated Thu Aug 24 08:59:59 CST 2023
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_admin
     *
     * @mbggenerated Thu Aug 24 08:59:59 CST 2023
     */
    int updateByPrimaryKey(Admin record);

    Admin selectByUsernameAndPwd(Admin admin);

    int totalAdmin();
}